name: Install ODBC SQL Server Driver

on: [push, pull_request]

jobs:
  install-odbc-driver:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install ODBC SQL Server Driver
      run: |
        sudo su
        # Download the Microsoft repository GPG keys
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

        # Register the Microsoft Ubuntu repository
        curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list

        # Update the package lists and install the driver
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

        # Optional: Install unixODBC development headers
        sudo apt-get install -y unixodbc-dev

    - name: Verify installation
      run: |
        odbcinst -q -d -n "ODBC Driver 18 for SQL Server"
  
